### ISSUE TITLE
Another lib :)

### ISSUE THREAD

**Issue by vitaly-t** [foxbunny/quickiter#20]
Just wanted to share a link to a similar project of mine - [iter-ops](https://github.com/vitaly-t/iter-ops).

b.t.w. did you abandon this project in the end?

**Comment by foxbunny** [comment]
> Just wanted to share a link to a similar project of mine - iter-ops.

Thanks for sharing. And you're [totally crazy](https://github.com/vitaly-t/iter-ops/blob/main/src/pipe.ts#L7-L17). :D

> b.t.w. did you abandon this project in the end?

I did. Two reasons:

1. The array operations are now highly optimized.
2. I've learned to code effectively without extra abstractions.

**Comment by vitaly-t** [comment]
> And you're totally crazy. :D

That's the standard way of providing complete type resolution within TypeScript. For examples, RXJS does it in the same way.

You can find more examples of it where types need to be merged, like operator [concat](https://github.com/vitaly-t/iter-ops/blob/main/src/ops/concat.ts).

> The array operations are now highly optimized.

Not as much as you think. Processing indexed iterables via index is still significantly faster than via the iterable interface. My library takes care of that fact [here](https://github.com/vitaly-t/iter-ops/blob/main/src/utils.ts#L19), by providing an iterable that uses indexes. That way, processing is way faster. B.T.W RXJS does the same thing internally. And processing arrays and all manually via indexes is kind of awkward these days :)

> I've learned to code effectively without extra abstractions.

Basic abstractions are the best, IMO, that's why I'm focusing on things that keep inputs+outputs 100% compatible with the JavaScript itself, no abstractions/synthetics on the output :)

**Comment by foxbunny** [comment]
Well, good for you. But no thanks. I don't find I really have a need for anything like `quickiter` or `iter-ops` myself.
